¡Hola, Alexis!

Mi nombre es Tonatiuh Cruz. Me complace revisar tu proyecto hoy.

Al identificar cualquier error inicialmente, simplemente los destacaré. Te animo a localizar y abordar los problemas de forma independiente como parte de tu preparación para un rol como data-scientist. En un entorno profesional, tu líder de equipo seguiría un emnfoque similar. Si encuentras la tarea desafiante, proporcionaré una pista más específica en la próxima iteración.

Encontrarás mis comentarios a continuación - **por favor no los muevas, modifiques o elimines**.

Puedes encontrar mis comentarios en cajas verdes, amarillas o rojas como esta:

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Éxito. Todo está hecho correctamente.
</div>

<div class="alert alert-block alert-warning">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Observaciones. Algunas recomendaciones.
</div>

<div class="alert alert-block alert-danger">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Necesita corrección. El bloque requiere algunas correcciones. El trabajo no puede ser aceptado con comentarios en rojo.
</div>

Puedes responderme utilizando esto:

<div class="alert alert-block alert-info">

In [ ]:
# importar librerías
import pandas as pd
from sqlalchemy import create_engine


db_config = {'user': 'practicum_student',         # nombre de usuario
             'pwd': 's65BlTKV3faNIGhmvJVzOqhs', # contraseña
             'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
             'port': 6432,              # puerto de conexión
             'db': 'data-analyst-final-project-db'}          # nombre de la base de datos

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(db_config['user'],
                                                                     db_config['pwd'],
                                                                       db_config['host'],
                                                                       db_config['port'],
                                                                       db_config['db'])

engine = create_engine(connection_string, connect_args={'sslmode':'require'})

In [ ]:
#Para empezar iniciaremos con visualizar todos los datasets en lenguaje SQL.
#En este codigo visualizaremos el dataset "books"
query_1 = '''
SELECT *
FROM books
LIMIT 10
'''

In [ ]:
pd.io.sql.read_sql(query_1, con = engine)

,book_id,author_id,title,num_pages,publication_date,publisher_id
0,1,546,'Salem's Lot,594,2005-11-01,93
1,2,465,1 000 Places to See Before You Die,992,2003-05-22,336
2,3,407,13 Little Blue Envelopes (Little Blue Envelope...,322,2010-12-21,135
3,4,82,1491: New Revelations of the Americas Before C...,541,2006-10-10,309
4,5,125,1776,386,2006-07-04,268
5,6,257,1st to Die (Women's Murder Club #1),424,2005-05-20,116
6,7,258,2nd Chance (Women's Murder Club #2),400,2005-05-20,116
7,8,260,4th of July (Women's Murder Club #4),448,2006-06-01,318
8,9,563,A Beautiful Mind,461,2002-02-04,104
9,10,445,A Bend in the Road,341,2005-04-01,116

In [ ]:
#En este codigo visualizaremos el dataset "authors"
query_2 = '''
SELECT *
FROM authors
LIMIT 10
'''

In [ ]:
pd.io.sql.read_sql(query_2, con = engine)

   author_id                                author
0          1                            A.S. Byatt
1          2        Aesop/Laura Harris/Laura Gibbs
2          3                       Agatha Christie
3          4                         Alan Brennert
4          5              Alan Moore/David   Lloyd
5          6                            Alan Paton
6          7           Albert Camus/Justin O'Brien
7          8                         Aldous Huxley
8          9    Aldous Huxley/Christopher Hitchens
9         10  Aleksandr Solzhenitsyn/H.T. Willetts

In [ ]:
#En este codigo visualizaremos el dataset "publishers"
query_3 = '''
SELECT *
FROM publishers
LIMIT 10
'''

In [ ]:
pd.io.sql.read_sql(query_3, con = engine)

   publisher_id                                publisher
0             1                                      Ace
1             2                                 Ace Book
2             3                                Ace Books
3             4                            Ace Hardcover
4             5        Addison Wesley Publishing Company
5             6                                  Aladdin
6             7                       Aladdin Paperbacks
7             8                             Albin Michel
8             9                          Alfred A. Knopf
9            10  Alfred A. Knopf Books for Young Readers

In [ ]:
#En este codigo visualizaremos el dataset "ratings"
query_4 = '''
SELECT *
FROM ratings
LIMIT 10
'''

In [ ]:
pd.io.sql.read_sql(query_4, con = engine)

   rating_id  book_id       username  rating
0          1        1     ryanfranco       4
1          2        1  grantpatricia       2
2          3        1   brandtandrea       5
3          4        2       lorichen       3
4          5        2    mariokeller       2
5          6        3  johnsonamanda       4
6          7        3    scotttamara       5
7          8        3    lesliegibbs       5
8          9        4    abbottjames       5
9         10        4   valenciaanne       4

In [ ]:
#En este codigo visualizaremos el dataset "reviews"
query_5 = '''
SELECT *
FROM reviews
LIMIT 10
'''

In [ ]:
pd.io.sql.read_sql(query_5, con = engine)

,review_id,book_id,username,text
0,1,1,brandtandrea,Mention society tell send professor analysis. ...
1,2,1,ryanfranco,Foot glass pretty audience hit themselves. Amo...
2,3,2,lorichen,Listen treat keep worry. Miss husband tax but ...
3,4,3,johnsonamanda,Finally month interesting blue could nature cu...
4,5,3,scotttamara,Nation purpose heavy give wait song will. List...
5,6,3,lesliegibbs,Analysis no several cause international.
6,7,4,valenciaanne,One there cost another. Say type save. With pe...
7,8,4,abbottjames,Within enough mother. There at system full rec...
8,9,5,npowers,Thank now focus realize economy focus fly. Ite...
9,10,5,staylor,Game push lot reduce where remember. Including...

In [ ]:
#Encuentra el número de libros publicados después del 1 de enero de 2000.
query_6 = '''
SELECT
    SUM(book_id) AS total_books
FROM
    books
WHERE
    publication_date > '2000-01-01'
'''

In [ ]:
pd.io.sql.read_sql(query_6, con = engine)

   total_books
0       407288

In [ ]:
#El número de libros publicados después del 01-01-2000 son 407,288.

In [ ]:
#Encuentra el número de reseñas de usuarios y la calificación promedio para cada libro.
query_7 = '''
SELECT
    ratings.book_id AS book_id,
    COUNT(reviews.review_id) AS review_id_cnt
FROM
    ratings
    INNER JOIN reviews ON reviews.book_id = ratings.book_id
GROUP BY
     ratings.book_id
ORDER BY
     ratings.book_id DESC;
'''

In [ ]:
pd.io.sql.read_sql(query_7, con = engine)

     book_id  review_id_cnt
0       1000             24
1        999              4
2        998             20
3        997             15
4        996              9
..       ...            ...
989        5             24
990        4              4
991        3              9
992        2              2
993        1              6

[994 rows x 2 columns]

In [ ]:
#En el código anterior se puede visualizar el número de reseñas de usuarios para cada libro.

In [ ]:
#Encuentra el número de reseñas de usuarios y la calificación promedio para cada libro.
query_8 = '''
SELECT
    ratings.book_id AS book_id,
    AVG(ratings.rating) AS rating_avg
FROM
    ratings
    INNER JOIN reviews ON reviews.book_id = ratings.book_id
GROUP BY
    ratings.book_id
ORDER BY
    ratings.book_id DESC;
'''

In [ ]:
pd.io.sql.read_sql(query_8, con = engine)

     book_id  rating_avg
0       1000    3.833333
1        999    4.500000
2        998    3.200000
3        997    3.400000
4        996    3.666667
..       ...         ...
989        5    4.000000
990        4    4.500000
991        3    4.666667
992        2    2.500000
993        1    3.666667

[994 rows x 2 columns]

In [ ]:
#En el código anterior se puede visualizar la calificación promedio para cada libro.

In [ ]:

#Identifica la editorial que ha publicado el mayor número de libros con más de 50 páginas.
query_9 = '''

SELECT
    publishers.publisher AS publisher_name,
    COUNT(books.publisher_id) AS publisher_cnt
FROM
    books
    INNER JOIN publishers ON books.publisher_id = publishers.publisher_id
WHERE
    num_pages > 50
GROUP BY
    publishers.publisher
ORDER BY
    publisher_cnt DESC;
'''

In [ ]:
pd.io.sql.read_sql(query_9, con = engine)

                                        publisher_name  publisher_cnt
0                                        Penguin Books             42
1                                              Vintage             31
2                             Grand Central Publishing             25
3                                     Penguin Classics             24
4                                     Ballantine Books             19
..                                                 ...            ...
329                                         Turtleback              1
330  Atheneum Books for Young Readers: Richard Jack...              1
331                                     Penguin Signet              1
332                                    Victor Gollancz              1
333                      Harvard Business Review Press              1

[334 rows x 2 columns]

In [ ]:
#El editorial que ha publicado el mayor número de libros con más de 50 páginas es Penguin Books.

In [ ]:
#Identifica al autor que tiene la más alta calificación promedio del libro: mira solo los libros con al menos 50 calificaciones.
query_10 = '''
SELECT
    books.title AS title,
    authors.author AS author,
    COUNT(ratings.book_id) AS book_id_cnt,
    MAX(ratings.rating) AS rating_max
FROM
    books
    INNER JOIN authors ON authors.author_id = books.author_id
    INNER JOIN ratings ON ratings.book_id = books.book_id
GROUP BY
     books.title, authors.author
HAVING
    COUNT(ratings.book_id) >= 50
ORDER BY
    book_id_cnt DESC, rating_max DESC;
'''

In [ ]:
pd.io.sql.read_sql(query_10, con = engine)

,title,author,book_id_cnt,rating_max
0,Twilight (Twilight #1),Stephenie Meyer,160,5
1,The Hobbit or There and Back Again,J.R.R. Tolkien,88,5
2,The Catcher in the Rye,J.D. Salinger,86,5
3,Angels & Demons (Robert Langdon #1),Dan Brown,84,5
4,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,82,5
5,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling/Mary GrandPré,80,5
6,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,75,5
7,Animal Farm,George Orwell/Boris Grabnar/Peter Škerl,74,5
8,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,74,5
9,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,73,5
10,Lord of the Flies,William Golding,71,5
11,Romeo and Juliet,William Shakespeare/Paul Werstine/Barbara A. M...,66,5
12,The Lightning Thief (Percy Jackson and the Oly...,Rick Riordan,62,5
13,Of Mice and Men,John Steinbeck,61,5
14,The Da Vinci Code (Robert Langdon #2),Dan Brown,59,5
15,The Alchemist,Paulo Coelho/Alan R. Clarke/Özdemir İnce,57,5
16,Memoirs of a Geisha,Arthur Golden,56,5
17,The Giver (The Giver #1),Lois Lowry,56,5
18,The Book Thief,Markus Zusak/Cao Xuân Việt Khương,53,5
19,Little Women,Louisa May Alcott,52,5

In [ ]:
#El autor que tiene la más alta calificación promedio del libro es Stephenie Meyer.

In [ ]:
#Encuentra el número promedio de reseñas de texto entre los usuarios que calificaron más de 50 libros.
query_11 = '''
SELECT
    username,
    ((COUNT(username) * 100 / 160)::real) AS username_avg,
    SUM(book_id) AS book_id_sum
FROM
    reviews
GROUP BY
     username
HAVING
    SUM(book_id) >= 50
ORDER BY
    username_avg DESC;
'''

In [ ]:
pd.io.sql.read_sql(query_11, con = engine)

           username  username_avg  book_id_sum
0           susan85          18.0        17203
1       sfitzgerald          17.0        11469
2         richard89          16.0        12855
3       lesliegibbs          16.0        13286
4           tanya01          16.0        14513
..              ...           ...          ...
155        samuel96           6.0         4261
156        daniel19           6.0         6578
157        joseph14           6.0         5024
158        robert00           5.0         4895
159  millernicholas           3.0         3171

[160 rows x 3 columns]

#En el código anterior se puede visualizar el número promedio de reseñas de los usuarios que calificaron mas de 50 libros.

<div class="alert alert-block alert-success">
<b>Paso 2</b> <a class="tocSkip"></a><br>
Has realizado un buen trabajo al formular una consulta SQL para contar con:
    
    - el número de libros publicados después de una fecha específica.
    - Calificación promedio
    - Editorial que ha publicado la mayor cantidad de libros
    - Autor con la calificación promedio más alta
    - Promedio de reseñas
    
Esto demuestra tu habilidad para manipular y consultar bases de datos de manera efectiva. Solamente para terminar de complementar te recomiendo incluir el número de libros evaluados por autor para proporcionar un contexto adicional sobre la consistencia de sus calificaciones.
</div>